import { Injectable, BadRequestException } from '@nestjs/common';
import { CreateDeploymentDto } from './dto/deployment.dto';
import { Template, Project } from '@prisma/client';

@Injectable()
export class DeploymentScriptsService {
  generateDockerDeployScript(
    projectName: string,
    deploymentId: string,
    template: Template | null,
    domain: string,
    isCustomDomain: boolean,
    dto?: CreateDeploymentDto,
    project?: Project | null,
  ): string {
    const repositoryUrl = dto?.repositoryUrl || project?.repositoryUrl;
    const imageName =
      repositoryUrl 
        ? `vpshub-${projectName.toLowerCase().replace(/[^a-z0-9]/g, '-')}-img-${deploymentId.slice(0, 5)}`
        : (dto?.dockerImage || project?.dockerImage || (template as any)?.image || 'nginx:alpine');
    
    const containerName = `vpshub-${projectName.toLowerCase().replace(/[^a-z0-9]/g, '-')}-${deploymentId.slice(0, 5)}`;
    const port = dto?.exposedPort || (project as any)?.exposedPort || (template as any)?.defaultPort || 80;
    const hostPort = 8000 + (parseInt(deploymentId.slice(0, 4), 16) % 1000);

    const rootDir = this.sanitizeRootDir(dto?.rootDir || (project as any)?.rootDir);
    const dockerfilePath = dto?.buildCmd || (project as any)?.buildCmd || 'Dockerfile';

    const sanitized = projectName.toLowerCase().replace(/[^a-z0-9]/g, '-');

    const projectNetwork = `vpshub-proj-${sanitized}`;
    
    // Construct environment variable flags for docker run
    let envFlags = '';
    if (dto?.env) {
      Object.entries(dto.env).forEach(([key, value]) => {
        envFlags += ` -e ${key}="${value.replace(/"/g, '\\"')}"`;
      });
    }

    // Construct Traefik labels
    let traefikLabels = '';
    if (domain) {
      // Use single quotes for labels in the shell script to avoid backtick expansion
      traefikLabels += ` --label 'traefik.enable=true'`;
      traefikLabels += ` --label 'traefik.http.routers.${sanitized}-${deploymentId.slice(0, 5)}.rule=Host(\`${domain}\`)'`;
      traefikLabels += ` --label 'traefik.http.routers.${sanitized}-${deploymentId.slice(0, 5)}.entrypoints=websecure'`;
      traefikLabels += ` --label 'traefik.http.routers.${sanitized}-${deploymentId.slice(0, 5)}.tls.certresolver=letsencrypt'`;
      if (port) {
        traefikLabels += ` --label 'traefik.http.services.${sanitized}-${deploymentId.slice(0, 5)}.loadbalancer.server.port=${port}'`;
      }
    }

    let dockerBuildStep = `
echo "[1/5] Pulling Docker image ${imageName}..."
sudo docker pull ${imageName} || { echo "Failed to pull image"; exit 1; }
`;

    if (repositoryUrl) {
      const appDir = `/opt/vpshub-apps/${sanitized}-${deploymentId.slice(0, 8)}`;
      dockerBuildStep = `
log "[0/5] Cloning repository and building Docker image..."
sudo rm -rf ${appDir} 2>/dev/null || true
sudo mkdir -p ${appDir}
log "Cloning ${repositoryUrl} into ${appDir}..."
sudo git clone ${repositoryUrl} ${appDir} || { log "Git clone failed"; exit 1; }
cd ${appDir}
log "Checking for root directory..."
if [ -n "${rootDir}" ]; then
  log "Switching to root directory: ${rootDir}"
  cd "${rootDir}" || { log "Root directory ${rootDir} not found"; exit 1; }
else
  log "Using current directory as root."
fi

log "Checking for docker-compose files..."
if [ -f "docker-compose.yml" ] || [ -f "docker-compose.yaml" ]; then
  log "SUCCESS: Detected docker-compose file."
  
  # Create .env file for docker-compose
  log "Generating .env file for Docker Compose..."
  echo "# Generated by VPSHub" > .env
  ${dto?.env ? Object.entries(dto.env).map(([k, v]) => `echo "${k}=${v.replace(/"/g, '\\"')}" >> .env`).join('\n  ') : ''}
  
  # Propagate .env to subdirectories if referenced in compose
  log "Scanning for additional required .env files..."
  COMPOSE_FILE=$( [ -f "docker-compose.yml" ] && echo "docker-compose.yml" || echo "docker-compose.yaml" )
  # Extract any .env paths mentioned
  ENV_PATHS=$(grep -E "\\.env" "$COMPOSE_FILE" | sed -E 's/.*[:[:space:]"'"'"']([^:[:space:]"'"'"']+\\.env).*/\\1/' | sort -u)
  for EP in $ENV_PATHS; do
    if [[ "$EP" == */* ]]; then
       EP_DIR=$(dirname "$EP")
       log "  Ensuring directory exists: $EP_DIR for $EP"
       mkdir -p "$EP_DIR"
       if [ ! -f "$EP" ]; then
         log "  Propagating .env to $EP"
         cp .env "$EP" 2>/dev/null || touch "$EP"
       fi
    fi
  done

  # Ensure core networks exist
  log "Ensuring core networks exist..."
  sudo docker network create vpshub-proxy 2>/dev/null || true
  sudo docker network create ${projectNetwork} 2>/dev/null || true

  # Use 'docker compose' (V2) if available, otherwise 'docker-compose' (V1)
  COMPOSE_CMD="docker-compose"
  if sudo docker compose version >/dev/null 2>&1; then
    COMPOSE_CMD="docker compose"
  fi

  # Automatic Subdomain Assignment using docker-compose.override.yml
  log "Generating docker-compose.override.yml for automatic routing..."
  
  # Get actual service names safely using docker compose config
  SERVICES=$(sudo $COMPOSE_CMD config --services 2>/dev/null)
  
  if [ -z "$SERVICES" ]; then
    log "WARNING: No services detected via config. Trying manual fallback..."
    COMPOSE_FILE=$( [ -f "docker-compose.yml" ] && echo "docker-compose.yml" || echo "docker-compose.yaml" )
    SERVICES=$(grep -E '^[[:space:]]{2}[a-zA-Z0-9_-]+:' "$COMPOSE_FILE" | sed 's/^[[:space:]]*//;s/://' | grep -v "networks" | grep -v "volumes" | grep -v "version")
  fi

  cat <<EOF > docker-compose.override.yml
services:
EOF

  for SERVICE in $SERVICES; do
    # Skip DB-like services (fix grep flags: remove 'u')
    if echo "$SERVICE" | grep -Eiv "db|postgres|redis|mysql|mongo|mail|cache" >/dev/null; then
       log "  Routing found for service: $SERVICE"
       SUBDOMAIN="$SERVICE.${domain}"
       
       cat <<EOT >> docker-compose.override.yml
  $SERVICE:
    networks:
      - vpshub-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${sanitized}-$SERVICE.rule=Host(\\\`$SUBDOMAIN\\\`)"
      - "traefik.http.routers.${sanitized}-$SERVICE.entrypoints=websecure"
      - "traefik.http.routers.${sanitized}-$SERVICE.tls.certresolver=letsencrypt"
EOT
    fi
  done

  cat <<EOT >> docker-compose.override.yml
networks:
  vpshub-proxy:
    external: true
EOT

  log "Executing $COMPOSE_CMD up -d --build --remove-orphans..."
  sudo $COMPOSE_CMD up -d --build --remove-orphans || { log "Docker Compose up failed"; exit 1; }
  
  USED_COMPOSE=true
else
  log "No docker-compose file found at root (or specified rootDir). Falling back to single-container Docker build."
  log "Building Docker image ${imageName} from ${dockerfilePath}..."
  sudo docker build -f ${dockerfilePath} -t ${imageName} . || { log "ERROR: Docker build failed"; exit 1; }
  log "SUCCESS: Docker image ${imageName} built."
fi
`;
    }

    return `
# Helper for logging
log() {
  echo "[$(date +'%Y-%m-%d %H:%M:%S')] [DOCKER-DEPLOY] $1"
}

log "--- Starting Docker Deployment Process ---"
log "Project: ${projectName}"
log "Deployment ID: ${deploymentId}"

${dockerBuildStep.trim()}

if [ "\${USED_COMPOSE:-false}" = "true" ]; then
  log "--- Docker Compose Deployment Completed ---"
else
  log "[2/5] Preparing to start single container ${containerName}..."
  log "Stopping and removing any existing container with same name..."
  sudo docker rm -f ${containerName} 2>/dev/null || true
  
  log "Ensuring Docker networks exist..."
  sudo docker network create vpshub-proxy 2>/dev/null || true
  sudo docker network create ${projectNetwork} 2>/dev/null || true

  log "Pulling image ${imageName} (if not built locally)..."
  sudo docker pull ${imageName} 2>/dev/null || true

  log "Running docker run for ${containerName}..."
  log "Command: sudo docker run -d --name ${containerName} --network vpshub-proxy --restart always ${imageName}"
  CONTAINER_ID=$(sudo docker run -d \
    --name ${containerName} \
    --restart always \
    --network vpshub-proxy \
    ${envFlags} \
    ${traefikLabels} \
    ${imageName}) || { log "ERROR: Failed to start container. Check image existence or label syntax."; exit 1; }
    
  log "SUCCESS: Container started with ID: \$CONTAINER_ID"
    
  log "Connecting container to project internal network ${projectNetwork}..."
  sudo docker network connect ${projectNetwork} ${containerName} || true
fi

log "--- Docker Deployment Successful ---"
log "Custom domain: ${domain} (Proxied through Traefik)"
`;
  }

  generateStaticDeployScript(
    projectName: string,
    deploymentId: string,
    template: Template | null,
    repositoryUrl: string,
    domain: string,
    isCustomDomain: boolean,
    appDir: string,
  ): string {
    const outputDir = (template as any)?.outputDir || '.';
    const installCmd = (template as any)?.installCmd || '';
    const buildCmd = (template as any)?.buildCmd || '';

    const sanitized = projectName.toLowerCase().replace(/[^a-z0-9]/g, '-');
    return `
# Helper for logging
log() {
  echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1"
}

log "[1/5] Cloning repository..."
sudo rm -rf ${appDir} 2>/dev/null || true
sudo mkdir -p ${appDir}
sudo git clone ${repositoryUrl} ${appDir} || { log "Git clone failed"; exit 1; }

cd ${appDir}
${installCmd ? `log "Installing dependencies..."; sudo ${installCmd} || { log "Install failed"; exit 1; }` : ''}
${buildCmd ? `log "Building project..."; sudo ${buildCmd} || { log "Build failed"; exit 1; }` : ''}

log "[2/5] Ensuring Nginx is installed..."
if ! command -v nginx >/dev/null 2>&1; then
  log "Nginx not found. Installing..."
  if command -v apt-get >/dev/null 2>&1; then
    sudo apt-get update -y -qq >/dev/null 2>&1
    sudo apt-get install -y -qq nginx >/dev/null 2>&1
  elif command -v yum >/dev/null 2>&1; then
    sudo yum install -y nginx >/dev/null 2>&1
  else
    log "Unsupported package manager. Install Nginx manually."
    exit 1
  fi
fi

# Ensure default Nginx site is disabled to avoid port 80 conflict
sudo rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true

if command -v systemctl >/dev/null 2>&1; then
  sudo systemctl enable nginx >/dev/null 2>&1 || true
  sudo systemctl start nginx >/dev/null 2>&1 || true
fi

# Assign a local port for Nginx to avoid conflict with Traefik (range 9000-9999)
LOCAL_PORT=$(( 9000 + (16#${deploymentId.slice(0, 4)} % 1000) ))

log "[3/5] Configuring Nginx (Port: $LOCAL_PORT) for static site ${domain}..."
sudo find /etc/nginx/sites-available/ -maxdepth 1 -name "vpshub-${sanitized}-*" ! -name "vpshub-${sanitized}-${deploymentId}" -exec rm -f {} + 2>/dev/null || true
sudo find /etc/nginx/sites-enabled/ -maxdepth 1 -name "vpshub-${sanitized}-*" ! -name "vpshub-${sanitized}-${deploymentId}" -exec rm -f {} + 2>/dev/null || true

sudo cat <<EOF > /etc/nginx/sites-available/vpshub-${sanitized}-${deploymentId}
server {
    listen \$LOCAL_PORT;
    server_name localhost;
    root ${appDir}/${outputDir};
    index index.html;

    location / {
        try_files \\$uri \\$uri/ /index.html;
    }
}
EOF
sudo ln -sf /etc/nginx/sites-available/vpshub-${sanitized}-${deploymentId} /etc/nginx/sites-enabled/
sudo nginx -t && sudo systemctl reload nginx || { log "Nginx config failed"; exit 1; }

log "[4/5] Configuring Traefik routing for static site..."
sudo mkdir -p /etc/vpshub/traefik/dynamic
sudo cat <<'EOF' > /etc/vpshub/traefik/dynamic/vpshub-${sanitized}-${deploymentId}.yml
http:
  routers:
    vpshub-${sanitized}-${deploymentId}:
      rule: "Host(\`${domain}\`)"
      service: vpshub-${sanitized}-${deploymentId}
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
  services:
    vpshub-${sanitized}-${deploymentId}:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:\$LOCAL_PORT"
EOF

log "Deployment successful!"
log "Custom domain: ${domain} (Proxied through Traefik to Nginx)"
`;
  }

  generateNodeDeployScript(
    projectName: string,
    deploymentId: string,
    template: Template | null,
    repositoryUrl: string,
    domain: string,
    isCustomDomain: boolean,
    appDir: string,
    sshUser: string,
    dto?: CreateDeploymentDto,
  ): string {
    const sanitized = projectName.toLowerCase().replace(/[^a-z0-9]/g, '-');
    const pm2Name = `vpshub-${sanitized}-${deploymentId.slice(0, 5)}`;

    const templatePort = (template as any)?.defaultPort || 3000;
    const basePort = templatePort >= 1024 ? templatePort : 3000;
    const port = basePort + (parseInt(deploymentId.slice(0, 4), 16) % 1000);

    const rootDir = this.sanitizeRootDir(dto?.rootDir);

    const installCmd = (
      dto?.installCmd ||
      (template as any)?.installCmd ||
      ''
    ).replace(/"/g, '\\"');
    const buildCmd = (
      dto?.buildCmd ||
      (template as any)?.buildCmd ||
      ''
    ).replace(/"/g, '\\"');
    const startCmd = (
      dto?.startCmd ||
      (template as any)?.startCmd ||
      ''
    ).replace(/"/g, '\\"');

    // Handle environment variables
    let envFileContent = '';
    if (dto?.env) {
      Object.entries(dto.env).forEach(([key, value]) => {
        envFileContent += `${key}=${value}\\n`;
      });
    }

    return `
set -euo pipefail

# Helper for logging
log() {
  echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1"
}

APP_USER="${sshUser}"
APP_DIR="${appDir}"
ROOT_DIR="${rootDir}"
PM2_NAME="${pm2Name}"
PORT=${port}
BASE_DIR="/var/www/vpshub-apps"

if [ -n "$ROOT_DIR" ]; then
  WORK_DIR="$APP_DIR/$ROOT_DIR"
else
  WORK_DIR="$APP_DIR"
fi

if [ -z "$APP_USER" ]; then
  APP_USER="$(id -un)"
fi

if [ "$(id -un)" = "$APP_USER" ]; then
  run_as_user() {
    bash -lc "$1"
  }
else
  run_as_user() {
    sudo -u "$APP_USER" -H bash -lc "$1"
  }
fi

log "[0/8] Preparing runtime..."
if ! command -v git >/dev/null 2>&1; then
  log "Git not found. Installing..."
  if command -v apt-get >/dev/null 2>&1; then
    sudo apt-get update -y -qq >/dev/null 2>&1
    sudo apt-get install -y -qq git >/dev/null 2>&1
  elif command -v yum >/dev/null 2>&1; then
    sudo yum install -y git >/dev/null 2>&1
  else
    log "Unsupported package manager. Install git manually."
    exit 1
  fi
fi

if ! command -v node >/dev/null 2>&1; then
  log "Node.js not found. Installing LTS..."
  if command -v apt-get >/dev/null 2>&1; then
    sudo apt-get update -y -qq >/dev/null 2>&1
    sudo apt-get install -y -qq curl ca-certificates >/dev/null 2>&1
    curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - >/dev/null 2>&1
    sudo apt-get install -y -qq nodejs >/dev/null 2>&1
  elif command -v yum >/dev/null 2>&1; then
    sudo yum install -y curl ca-certificates >/dev/null 2>&1
    curl -fsSL https://rpm.nodesource.com/setup_20.x | sudo bash - >/dev/null 2>&1
    sudo yum install -y nodejs >/dev/null 2>&1
  else
    log "Unsupported package manager. Install Node.js manually."
    exit 1
  fi
fi

if ! command -v pm2 >/dev/null 2>&1; then
  log "PM2 not found. Installing..."
  sudo npm install -g pm2 || { log "PM2 install failed"; exit 1; }
fi

if ! command -v nginx >/dev/null 2>&1; then
  log "Nginx not found (for reverse proxy). Installing..."
  if command -v apt-get >/dev/null 2>&1; then
    sudo apt-get update -y -qq >/dev/null 2>&1
    sudo apt-get install -y -qq nginx >/dev/null 2>&1
  elif command -v yum >/dev/null 2>&1; then
    sudo yum install -y nginx >/dev/null 2>&1
  fi
fi

# Ensure default Nginx site is disabled to avoid port 80 conflict
sudo rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true

if command -v systemctl >/dev/null 2>&1; then
  sudo systemctl enable nginx >/dev/null 2>&1 || true
  sudo systemctl start nginx >/dev/null 2>&1 || true
fi

sudo mkdir -p "$BASE_DIR"
sudo chown -R "$APP_USER":"$APP_USER" "$BASE_DIR"

log "[1/8] Cloning repository..."
run_as_user "rm -rf '$APP_DIR'"
run_as_user "mkdir -p '$APP_DIR'"
run_as_user "git clone --depth 1 '${repositoryUrl}' '$APP_DIR' || { log 'Git clone failed'; exit 1; }"

log "[2/8] Creating .env file..."
if [ -n "${envFileContent}" ]; then
  run_as_user "printf \\"${envFileContent}\\" > '$WORK_DIR/.env'"
else
  run_as_user "touch '$WORK_DIR/.env'"
fi

log "[3/8] Installing dependencies..."
if [ -n "${installCmd}" ]; then
  run_as_user "cd '$WORK_DIR' && ${installCmd}"
else
  run_as_user "cd '$WORK_DIR' && npm install"
fi

log "[4/8] Building application..."
if [ -n "${buildCmd}" ]; then
  run_as_user "cd '$WORK_DIR' && ${buildCmd}"
fi

log "[5/8] Starting application with PM2 on port $PORT..."
run_as_user "pm2 delete '$PM2_NAME' 2>/dev/null || true"
if [ -n "${startCmd}" ]; then
  run_as_user "cd '$WORK_DIR' && PORT=$PORT NODE_ENV=production pm2 start bash --name '$PM2_NAME' -- -lc \\"${startCmd}\\""
else
  run_as_user "cd '$WORK_DIR' && PORT=$PORT NODE_ENV=production pm2 start npm --name '$PM2_NAME' -- start"
fi
run_as_user "pm2 save"

log "[6/8] Configuring Nginx (Local Proxy)..."
# Assign a local port for Nginx to proxy (range 10000-10999)
LOCAL_NGINX_PORT=$(( 10000 + (16#${deploymentId.slice(0, 4)} % 1000) ))
# Config Nginx to listen on a local port and proxy to the Node app
sudo cat <<EOF > /etc/nginx/sites-available/vpshub-${sanitized}-${deploymentId}
server {
    listen \$LOCAL_NGINX_PORT;
    server_name localhost;

    location / {
        proxy_pass http://127.0.0.1:$PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \\$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \\$host;
        proxy_cache_bypass \\$http_upgrade;
    }
}
EOF
sudo ln -sf /etc/nginx/sites-available/vpshub-${sanitized}-${deploymentId} /etc/nginx/sites-enabled/
sudo nginx -t && sudo systemctl reload nginx || { log "Nginx config failed"; exit 1; }

log "[7/8] Configuring Traefik routing for Node.js app..."
sudo mkdir -p /etc/vpshub/traefik/dynamic
sudo cat <<'EOF' > /etc/vpshub/traefik/dynamic/vpshub-${sanitized}-${deploymentId}.yml
http:
  routers:
    vpshub-${sanitized}-${deploymentId}:
      rule: "Host(\`${domain}\`)"
      service: vpshub-${sanitized}-${deploymentId}
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
  services:
    vpshub-${sanitized}-${deploymentId}:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:\$LOCAL_NGINX_PORT"
EOF

log "Deployment successful!"
log "Custom domain: ${domain} (Routes: Traefik -> Nginx -> PM2)"
`;
  }

  generateSslScript(
    domain: string,
    isCustomDomain: boolean,
    stepNum: number = 4,
  ): string {
    if (!isCustomDomain) {
      return `echo "[${stepNum}/${stepNum}] Skipping SSL for platform domain..."`;
    }
    return `
echo "[${stepNum}/${stepNum}] Provisioning SSL via Certbot..."
if ! command -v certbot >/dev/null 2>&1; then
  echo "Certbot not found. Installing..."
  if command -v apt-get >/dev/null 2>&1; then
    sudo apt-get update -y -qq
    sudo apt-get install -y -qq certbot python3-certbot-nginx
  elif command -v yum >/dev/null 2>&1; then
    sudo yum install -y epel-release
    sudo yum install -y certbot python3-certbot-nginx
  else
    echo "Unsupported package manager. Please install certbot manually."
  fi
fi

sudo certbot --nginx -d ${domain} --non-interactive --agree-tos -m admin@vpshub.link || echo "Certbot failed, falling back to HTTP"
`;
  }

  private sanitizeRootDir(rootDir?: string | null): string {
    if (!rootDir) return '';
    const trimmed = rootDir.trim();
    if (!trimmed) return '';
    if (trimmed.startsWith('/') || trimmed.startsWith('~')) {
      throw new BadRequestException('Root directory must be a relative path');
    }
    if (trimmed.includes('..')) {
      throw new BadRequestException('Root directory cannot contain ".."');
    }
    if (!/^[a-zA-Z0-9._/-]+$/.test(trimmed)) {
      throw new BadRequestException(
        'Root directory contains invalid characters',
      );
    }
    return trimmed.replace(/\/+$/, '');
  }

  generateCleanupScript(projectName: string, deploymentIds: string[]): string {
    const sanitized = projectName.toLowerCase().replace(/[^a-z0-9]/g, '-');
    const appDirPrefix = `/var/www/vpshub-apps/${sanitized}-`;

    let pm2Cleanup = '';
    let dockerCleanup = '';
    let nginxCleanup = '';
    let dirCleanup = '';

    deploymentIds.forEach((id) => {
      const pm2Name = `vpshub-${sanitized}-${id.slice(0, 5)}`;
      const containerName = `vpshub-${sanitized}-${id.slice(0, 5)}`;
      const imageName = `vpshub-${sanitized}-img-${id.slice(0, 5)}`;
      const projectNetwork = `vpshub-proj-${sanitized}`;

      pm2Cleanup += `pm2 delete "${pm2Name}" 2>/dev/null || true\n`;
      dockerCleanup += `sudo docker rm -f "${containerName}" 2>/dev/null || true\n`;
      dockerCleanup += `sudo docker rmi -f "${imageName}" 2>/dev/null || true\n`;
      dockerCleanup += `sudo docker network rm "${projectNetwork}" 2>/dev/null || true\n`;

      nginxCleanup += `sudo rm -f /etc/nginx/sites-available/vpshub-${sanitized}-${id}\n`;
      nginxCleanup += `sudo rm -f /etc/nginx/sites-enabled/vpshub-${sanitized}-${id}\n`;
      nginxCleanup += `sudo rm -f /etc/vpshub/traefik/dynamic/vpshub-${sanitized}-${id}.yml\n`;
      dirCleanup += `sudo rm -rf "${appDirPrefix}${id.slice(0, 8)}"\n`;
      dirCleanup += `sudo rm -rf "/opt/vpshub-apps/${sanitized}-${id.slice(0, 8)}"\n`;
    });

    return `
echo "Starting cleanup for project ${projectName}..."

echo "[1/3] Stopping PM2 processes and Docker containers..."
${pm2Cleanup}
pm2 save || true
${dockerCleanup}

echo "[2/3] Removing Nginx configurations..."
${nginxCleanup}
sudo nginx -t && sudo systemctl reload nginx || true

echo "[3/3] Deleting project directories..."
${dirCleanup}

echo "Cleanup completed successfully!"
`;
  }
}
